### ISSUE TITLE
[RFC] Proposal for vechicle repair shop modules, maybe a new vertical repo

### ISSUE THREAD

**Issue by rpsjr** [OCA/fleet#126]
Hi everyone,

I am working on an Odoo project with the purpose of serving vehicle repair shop businnes.

I understand that the fleet module is designed for the management and use of vehicles by the company that uses Odoo itself and, maybe, the best desing must reveal to build a new vertical like repo, such as vertical-vechicle-repair-shop.

Anyway, the fleet repo must be the start point to extend some features to be able to attend this project.

Initial Scope

> Integrate the **fleet.vehicle** with the **res.partner** as owner (add vehicle ownership, linking to custumers to vehicles)

> Integrate the **fleet.vehicle** with the **sale** and **account.move.line** model (link sales and invoice to veichicles)

> Integrate the **fleet.vehicle.model** with the **products** model as owner (link btw parts and vehicle models)
The idea is to have a vertical auto (vehicle) repair shop, where the major requirements is to link purchase and invoice (maybe lines) to vehicle, add vehicle ownership, linking to contacts and also link purchases to vehicle model. 

Modules that I intend to implement and make available at OCA

- [x] fleet_vehicle_ownership >> #127 
- [ ] fleet_vehicle_repair_shop_sale
- [ ] fleet_vehicle_repair_shop_part_product

What do you think of the modules mentioned above?

cc @ivantodorovich @mamcode @sbidoul @mymage @brian10048 @marcelsavegnago @pedrobaeza

**Comment by mymage** [comment]
Hi Raimundo,
   on what (not very much) I know about the Odoo and specifically OCA logic on the features/mudules development, the reuse and integration with existing modules/data structures is preferred on creating new one.
   So if I would have to develop a similar features I would look to the maintenance module. I think that here there are a series of features that can be simly adapted to a "vechicle repair" and the activty management trought timesheet can support the "shop" part.
   For me it is better to add modules on the fleet repo than create a new one, so there will be a complete set of feature for fleet management.
   But I'm courious to know the opnion of who is more expert than me.

   Surely I appreciate your proposal to share the idea and  do it on OCA than with "personal" mudules, I I will do my best to support your project.

   Ciao

   Da "Raimundo Pereira da Silva Junior" ***@***.***
   A "OCA/fleet" ***@***.***
   Cc "Stefano Consolaro" ***@***.***,"Mention" ***@***.***
   Data Thu, 09 Nov 2023 10:17:18 -0800
   Oggetto [OCA/fleet] [RFC] Proposal for vechicle repair shop modules, maybe a new vertical repo (Issue #126)

   Hi everyone,

   I am working on an Odoo project with the purpose of serving vehicle repair shop businnes.

   I understand that the fleet module is designed for the management and use of vehicles by the company that uses Odoo itself and, maybe, the best desing must reveal to build a new vertical like repo, such as vertical-vechicle-repair-shop.

   Anyway, the fleet repo must be the start point to extend some features to be able to attend this project.

   Initial Scope

     Integrate the fleet.vehicle with the res.partner as owner (add vehicle ownership, linking to custumers to vehicles)

     Integrate the fleet.vehicle with the sale and account.move.line model (link sales and invoice to veichicles)

     Integrate the fleet.vehicle.model with the products model as owner (link btw parts and vehicle models)
     The idea is to have a vertical auto (vehicle) repair shop, where the major requirements is to link purchase and invoice (maybe lines) to vehicle, add vehicle ownership, linking to contacts and also link purchases to vehicle model.

   Modules that I intend to implement and make available at OCA
     * [_] fleet_vehicle_ownership
     * [_] fleet_vehicle_repair_shop_sale
     * [_] fleet_vehicle_repair_shop_part_product

   What do you think of the modules mentioned above?

   And what do you think of the project in general? I'm still thinking about the rental revenue management, I know it has the sale_rental module but I haven't analyzed it yet.

   cc @ivantodorovich @mamcode @sbidoul @mymage @brian10048 @marcelsavegnago @pedrobaeza

   —
   Reply to this email directly, view it on GitHub, or unsubscribe.
   You are receiving this because you were mentioned. Message ID: ***@***.***>

   Stefano Consolaro
   www.mymage.it

**Comment by pedrobaeza** [comment]
Yes, the first module `fleet_vehicle_ownership` seems interesting to be hosted on OCA/fleet, as you have already done, and the rest can be named `repair_vehicle...` and be hosted on OCA/maintenance.

**Comment by mymage** [comment]
Hi Pedro,

   let me understand: why you indicate do add the repair_vehicle in maintenance repo instead the fleet repo?
   For me the logic is that you ad a "feature" (the maintenance) to the vehicle not a vehicle to a maintenance.

   Thanks

   Da "Pedro M. Baeza" ***@***.***
   A "OCA/fleet" ***@***.***
   Cc "Stefano Consolaro" ***@***.***,"Mention" ***@***.***
   Data Thu, 09 Nov 2023 23:39:19 -0800
   Oggetto Re: [OCA/fleet] [RFC] Proposal for vechicle repair shop modules, maybe a new vertical repo (Issue #126)

   Yes, the first module fleet_vehicle_ownership seems interesting to be hosted on OCA/fleet, as you have already done, and the rest can be named repair_vehicle... and be hosted on OCA/maintenance.

   —
   Reply to this email directly, view it on GitHub, or unsubscribe.
   You are receiving this because you were mentioned. Message ID: ***@***.***>

   Stefano Consolaro
   www.mymage.it

**Comment by pedrobaeza** [comment]
My reasoning path is that the first name is the one where you are going to introduce things, so here it seems that hosting things in the "Maintenance" section, but maybe a new section should be done, and prefix modules with other name, like `mechanical_repair_*`, `auto_repair_*`, `vehicle_repair_*`, or any of the most suitable names you think.

**Comment by marcelsavegnago** [comment]
I agree that starting our efforts with the Fleet_vehicle_ownership module is a prudent choice :)

As for integration with the repair module, I am inclined to believe that this is a strategic direction. My understanding is that a significant part of the solutions for parts replacement, billing processes and related tasks can be managed effectively by the repair module. If we proceed with this integration, it is feasible to consider developing modules both within the oca/fleet and oca/repair repositories, possibly extending to others as maintenance. However, the suitability of a vertical in this context is something I'm unsure about and would require further evaluation.

If there is integration of the fleet with the stock, the entry of the vehicle can be done via picking, the vehicle would be a product with a series :D and with this it would be possible to have traceability of all parts and exchanges just by observing the traceability of the series.

This module already makes it possible to use the vehicle for repairs.
https://github.com/OCA/fleet/tree/14.0/fleet_vehicle_stock
