### ISSUE TITLE
Module fleet_analytic_account

### ISSUE THREAD

**Issue by yweng8111** [OCA/fleet#22]
We have created a Module to Link fleet members to analytic accounts in order to track costs and revenues associated to the vehicle. Corresponding analytic entries can be reached from a fleet member form view via smart button. Before migrating to v12 and doing the finalization and PR we wanted to speak out hear if anyone is working on similar approaches

**Comment by pedrocs-exo** [comment]
Hi,

The feature you're proposing is very helpful. If you need help just let me know.

**Comment by mymage** [comment]
Hi, I speak in general without knowing much on Odoo way to manage costs.
For me an "analytic account" is a way to collect costs/revenues per type (electricity, employees, external services, ...).
Another way to view economic data is for destination (machine, framework, department, ...).
A fleet member can be generalized as "cost center" so I think that it would be better to connect a cost center than directly an analytic account.
Associating the relative economic moovment to a cost center and to an analytic account, you can improove your analysis with better details.

**Comment by pedrocs-exo** [comment]
Hello,

In general terms, all you say is correct. In practical Odoo terms, I think you should associate fleet members with analytic accounts because that's the standard way of doing it in Odoo. If you want to support cost centers through the specific [OCA addon](https://github.com/OCA/account-financial-tools/tree/12.0/account_cost_center) I suggest you do it in a second extension module.

Again, let me know if you want help. I can review you module before or after the PR.
